### ISSUE TITLE
No working any more

### ISSUE THREAD

**Issue by uziel200** [PsykoSoldi3r/vscode-itunes#25]
**Description**

Stop working a couple of version early. I get de following error:

```
[Extension Host] Error: /Users/user/.vscode/extensions/psykosoldi3r.itunes-vscode-0.16.5/scripts/music/en/currentTrack.applescript:107:110: execution error: Music detectó un error: No puede obtenerse artist of current track. (-1728)
```

```
at ChildProcess.<anonymous> (/Users/user/.vscode/extensions/psykosoldi3r.itunes-vscode-0.16.5/node_modules/applescript/lib/applescript.js:49:13)	at ChildProcess.emit (events.js:315:20)	at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

**macOS version**

v11.2.3

**vscode Version**

v1.54.3

**Comment by uziel200** [comment]
It seems is a stream only issue of macOS  

https://developer.apple.com/forums/thread/669239

**Comment by uziel200** [comment]
macOS Big Sur 11.3 solve this issue

**Comment by joeykamsteeg** [comment]
Thanks! @uziel200
